// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4M2Mrm-acY77-iiJFpPTEbRt8qgnjiLA',
    appId: '1:253576298933:web:e337c89b16c10ab55459fc',
    messagingSenderId: '253576298933',
    projectId: 'rdcbausher',
    authDomain: 'rdcbausher.firebaseapp.com',
    storageBucket: 'rdcbausher.firebasestorage.app',
    measurementId: 'G-E00PLL9Y2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsoLjuCKCGLpzMGKvNeSllQNhycebztQ',
    appId: '1:253576298933:android:fb54887fc99c78625459fc',
    messagingSenderId: '253576298933',
    projectId: 'rdcbausher',
    storageBucket: 'rdcbausher.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJaCg7ACZnZCP9H3u5VGpmxLtkxGwcW_I',
    appId: '1:253576298933:ios:8178ea62111176735459fc',
    messagingSenderId: '253576298933',
    projectId: 'rdcbausher',
    storageBucket: 'rdcbausher.firebasestorage.app',
    iosBundleId: 'com.example.invbausherrecording',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJaCg7ACZnZCP9H3u5VGpmxLtkxGwcW_I',
    appId: '1:253576298933:ios:8178ea62111176735459fc',
    messagingSenderId: '253576298933',
    projectId: 'rdcbausher',
    storageBucket: 'rdcbausher.firebasestorage.app',
    iosBundleId: 'com.example.invbausherrecording',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4M2Mrm-acY77-iiJFpPTEbRt8qgnjiLA',
    appId: '1:253576298933:web:f87466997d1cc0e65459fc',
    messagingSenderId: '253576298933',
    projectId: 'rdcbausher',
    authDomain: 'rdcbausher.firebaseapp.com',
    storageBucket: 'rdcbausher.firebasestorage.app',
    measurementId: 'G-XE9WNQY32P',
  );
}
